services:
    crafty:
        container_name: crafty_container
        image: registry.gitlab.com/crafty-controller/crafty-4:latest
        restart: always
        network_mode: "service:tailscale"
        environment:
            - TZ=Etc/UTC
        ports: []
        volumes:
            - ./docker/backups:/crafty/backups
            - ./docker/logs:/crafty/logs
            - ./docker/servers:/crafty/servers
            - ./docker/config:/crafty/app/config
            - ./docker/import:/crafty/import
    tailscale:
        image: tailscale/tailscale:latest
        container_name: tailscale
        hostname: minecraft-server
        environment:
            - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}  # REPLACE THIS
            - TS_STATE_DIR=/var/lib/tailscale
            - TS_USERSPACE=true
        volumes:
            - ./ts-state:/var/lib/tailscale
        cap_add:
            - NET_ADMIN
            - NET_RAW
            - SYS_MODULE
        devices:
            - /dev/net/tun:/dev/net/tun
        restart: unless-stopped
